#!/bin/bash

###################################################
## This script burn-in drains in a gridded DEM
#
# Usage: ./AddDrains inpuDEM.nc drains.shp outputDEM.nc

# Input DEM s .nc file
originalnc=$1

# drains shape file should be a line type with at least 4 column id, width, elevation start of line feature , elevation end of line feature
drainsshp=$2

# Output file name  .nc file
outputnc=$3




gridres=`grdinfo -C ${originalnc} | awk '{printf("%d",$8)}'`

echo ${gridres}
#use 15m search radius
if [[ $4 == "" ]]
then
  searchrad=15.0
else
  searchrad=$4
fi




## Convert stuctures to GMT file
ogr2ogr -f "OGR_GMT" New_flow_Struct.gmt ${drainsshp}

# z value is not a 3rd column so interpolate the z value to the specifed in shp file
awk 'BEGIN{w=0.0; zs=0.0; ze=0.0;}{if($1=="#"){split($2,d,"|"); w=d[2]; zs=d[3]; ze=d[4]}else{if($1==">"){print($1)}else{print($1,$2,w,zs,ze)}}}' New_flow_Struct.gmt > Flow_struct_seg.tmp

# Calculate total length of segments
gmtspatial Flow_struct_seg.tmp -Q+h > Flow_struct_seg+len.tmp

# calculate z values at Structure nodes
awk 'BEGIN{len=0.0; TL=0.0; xo=-1.0; yo=-1.0}{if($1==">"){ split($2,d,"Z"); TL=d[2]; len=0.0; xo=-1.0; yo=-1.0; print($1)}else{if(xo<0.0){len=0.0;xo=$1; yo=$2;}; dx=xo-$1; dy=yo-$2; len=len+sqrt(dx*dx+dy*dy); print($1,$2,$3,$4+($5-$4)*(len/TL)); xo=$1; yo=$2;}}' Flow_struct_seg+len.tmp > Flow_struct_seg+len+z.tmp

#interpolate structures nodes to the model resolution
sample1d  Flow_struct_seg+len+z.tmp -I${gridres}c -Af > Flow_struct_seg_resampled.tmp


#Mask the grid along the structure footprint using the width specified in the file
grdmask Flow_struct_seg_resampled.tmp -R${originalnc} -Sz -N0/1/1 -GStruct_area-tmp.nc

# Create a grid with values of elevation from the structures only
nearneighbor Flow_struct_seg_resampled.tmp -i0,1,3 -R${originalnc} -N1 -S${searchrad} -Gstruct_Elevation-tmp.nc

# copy the structure elevation only in the structure footprint
grdmath Struct_area-tmp.nc 0 NAN struct_Elevation-tmp.nc MUL = struct_Elevation-tmp.nc

# Copy DEM for footprint of the structures
grdmath Struct_area-tmp.nc 0 NAN ${originalnc} MUL = DEM_at_struct-tmp.nc

# for Drains/Stopbanks only use the structure topograhy if it is below/above the DEM
### FOR DRAINS ONLY
grdmath DEM_at_struct-tmp.nc struct_Elevation-tmp.nc MIN = Struct_Fix-tmp.nc

### For STOPBANKS ONLY
# grdmath DEM_at_struct.nc struct_Elevation.nc MAX = Struct_Fix.nc

grdmath Struct_Fix-tmp.nc ${originalnc} DENAN = ${outputnc}

rm Struct_Fix-tmp.nc DEM_at_struct-tmp.nc struct_Elevation-tmp.nc Struct_area-tmp.nc Flow_struct_seg_resampled.tmp

rm New_flow_Struct.gmt Flow_struct_seg+len.tmp Flow_struct_seg.tmp  Flow_struct_seg+len+z.tmp Flow_struct_seg_resampled.tmp
